ID2LABEL = {0: 'Neutral',
            1: 'Happy',
            2: 'Sad',
            3: 'Surprise',
            4: 'Fear',
            5: 'Disgust',
            6: 'Anger',
            7: 'Contempt',
            8: 'None'}

ID2EXPRESSION = {0: 'Neutral',
                 1: 'Happy',
                 2: 'Sad',
                 3: 'Surprise',
                 4: 'Fear',
                 5: 'Disgust',
                 6: 'Anger',
                 7: 'Contempt',
                 8: 'None',
                 9: 'Uncertain',
                 10: 'No-Face'}
